# Generated by Django 5.2.1 on 2025-06-04 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('LN', 'LEMON'), ('OL', 'OOLONG'), ('EL', 'ELAICHI')], max_length=2)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
